version: '3'

vars:
  API_SERVICE_PORT: 8080
  STORAGE_SERVICE_PORT: 50051
  PROCESSOR_SERVICE_PORT: 50051

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  proto:generate:
    desc: Generate Go code from proto definitions
    cmds:
      - buf generate

  deps:update:
    desc: Update Go dependencies
    cmds:
      - go mod tidy
      - go mod verify

  lint:
    desc: Run linters and static analysis
    cmds:
      - buf lint
      - go vet ./...
  
  services:up:
    desc: Start all services
    cmds:
      - task services:upload
      - task services:storage
      - task services:processor
  services:upload:
    desc: Start FileUpload service
    cmds:
      - go run ./services/api-gateway-service/cmd/server/main.go
  services:storage:
    desc: Start FileStorage service
    cmds:
      - go run ./services/file-storage-service/cmd/server/main.go
  services:processor:
    desc: Start FileProcessor service
    cmds:
      - go run ./services/file-processor-service/cmd/server/main.go
  services:client:
    desc: Start FileStorage service
    cmds:
      - go run ./tools/clients/file_storage_client.go
  test:
    desc: Run all tests
    cmds:
      - go test ./.../unit/...
      - go test ./.../integration/...
      - go test ./.../performance/...

  test:unit:
    desc: Run unit tests
    cmds:
      - go test ./.../unit/...

  test:integration:
    desc: Run integration tests
    cmds:
      - go test ./.../integration/...

  test:performance:
    desc: Run performance tests
    cmds:
      - go test -benchmem -benchtime=5x -bench=. -benchmem ./.../performance/...

  test:coverage:
    desc: Generate test coverage report
    cmds:
      - go test -coverprofile=coverage.out ./... 
      - go tool cover -html=coverage.out -o coverage.html

  clean:
    desc: Clean generated files and caches
    cmds:
      - rm -rf gen/
      - go clean ./...