server:
  host: 0.0.0.0
  port: 50051

logging:
  level: info
  json_format: true
  development: false

database:
  driver: sqlite
  path: /data/storage.db

nats:
  servers: 
    - nats://localhost:4222
  cluster: upload-store-cluster

storage:
  provider: local
  base_path: /data/uploads

jwt:
  secret: "secret_key"
  issuer: "myservice"